/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ui.components.CourseCell;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import model.*;
import ui.components.AssignmentCell;

/**
 *
 * @author Ke
 */
public class AssignmentJPanel extends javax.swing.JPanel {
    JPanel container;
    Course course;
    String content;
    String name;
    Assignment.AssignmentType type;

    public AssignmentJPanel(JPanel container, Course course) {
        initComponents();
        this.container=container;
        this.course=course;
        initAssignments(course.getAssignmentDirectory());
    }

    private void initAssignments(AssignmentDirectory assignmentDir){

        contentPanel.setLayout(new GridLayout(0,2));

        int cell_H = contentPanel.getWidth() * 4 / 3;

        for (Assignment assignment : assignmentDir){
            AssignmentCell cell = new AssignmentCell(assignment);
            contentPanel.add(cell);
            cell.setPreferredSize(new Dimension(contentPanel.getWidth(),contentPanel.getWidth() * 4 / 3));
        }

        scrollPanel.setSize(contentPanel.getWidth(), cell_H * assignmentDir.getList().size() / 2 + 1);

        contentPanel.setSize(contentPanel.getWidth(), cell_H * assignmentDir.getList().size() / 2 + 1);

        contentPanel.setPreferredSize(new Dimension(contentPanel.getWidth(), cell_H * assignmentDir.getList().size() / 2 + 1));
        updateUI();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1024, 768));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2105, Short.MAX_VALUE)
        );

        scrollPanel.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 2107, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
