/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.awt.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import model.*;

/**
 * @author adinanibijiang
 */
public class MainJFrame extends javax.swing.JFrame {
    //private StudentDirectory studentDirectory = new StudentDirectory();
    private Data data = new Data();

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        data.run();
        initComponents();
        this.setSize(1024, 768);
        Router.getInstance(this);
        Global.getInstance().setFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        userProcessContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LoginJPanel = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        accountTypeCheckBox = new javax.swing.JCheckBox();
        loginJButton1 = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(150);

        userProcessContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Skia", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(99, 148, 249));
        jLabel3.setText("Learning Management System");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 230, 720, 120);

        jLabel4.setText("@ Team 8");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(590, 400, 100, 18);

        userProcessContainer.add(jPanel1, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        LoginJPanel.setBackground(new java.awt.Color(51, 153, 255));
        LoginJPanel.setLayout(null);

        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });
        LoginJPanel.add(loginJButton);
        loginJButton.setBounds(10, 330, 130, 37);
        LoginJPanel.add(userNameJTextField);
        userNameJTextField.setBounds(10, 170, 118, 24);

        jLabel1.setFont(new java.awt.Font("PingFang HK", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");
        LoginJPanel.add(jLabel1);
        jLabel1.setBounds(10, 140, 90, 20);

        jLabel2.setFont(new java.awt.Font("PingFang HK", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        LoginJPanel.add(jLabel2);
        jLabel2.setBounds(10, 210, 70, 20);
        LoginJPanel.add(loginJLabel);
        loginJLabel.setBounds(132, 588, 0, 0);

        accountTypeCheckBox.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        accountTypeCheckBox.setText("I'm an instructor");
        accountTypeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypeCheckBoxActionPerformed(evt);
            }
        });
        LoginJPanel.add(accountTypeCheckBox);
        accountTypeCheckBox.setBounds(10, 270, 130, 25);

        loginJButton1.setText("New Student");
        loginJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButton1ActionPerformed(evt);
            }
        });
        LoginJPanel.add(loginJButton1);
        loginJButton1.setBounds(10, 480, 130, 37);

        passwordField.setToolTipText("*");
        LoginJPanel.add(passwordField);
        passwordField.setBounds(10, 230, 120, 24);

        jSplitPane1.setLeftComponent(LoginJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed

        String userName = userNameJTextField.getText();
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        User user = User.authenticateUser(userName, password, isInstructor ? 1 : 0);

        if (user == null) {
            JOptionPane.showMessageDialog(null, "Wrong username or wrong password");
        } else {
            Global.getInstance().login(user);
            if(user.getType() == 1){
                // Instructor
                InstructorHome home = new InstructorHome((Instructor) user);
                Router.getInstance(null).go(home);
            }else{
                StudentHome mainJPanel = new StudentHome((Student)user);
                changeContentPane(mainJPanel);
            }
        }
    }//GEN-LAST:event_loginJButtonActionPerformed


    // change content
    public void changeContentPane(Container contentPane) {
        Router.getInstance(null).go(contentPane);
    }

    private boolean isInstructor = false;

    private void accountTypeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypeCheckBoxActionPerformed
        // TODO add your handling code here:
        isInstructor = accountTypeCheckBox.isSelected();
    }//GEN-LAST:event_accountTypeCheckBoxActionPerformed

    private void loginJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButton1ActionPerformed
        // TODO add your handling code here:
        StudentRegister studentregister = new StudentRegister();
        jSplitPane1.setRightComponent(studentregister);
    }//GEN-LAST:event_loginJButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginJPanel;
    private javax.swing.JCheckBox accountTypeCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JButton loginJButton1;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
